name: Generate & Publish Wiki Docs with Sphinx

on:
  push:
    branches: [ main ] # Ensure this matches your main branch name

permissions:
  contents: write # For checking out code, wiki, and pushing to wiki

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or '3.11', Sphinx is generally compatible
          
      - name: Setup and Build Sphinx Documentation
        env: # Environment variables for this step
          SPHINX_SOURCE_DIR: "_sphinx_doc_source"
          SPHINX_BUILD_DIR: "_build"
        run: |
          echo "Starting Sphinx setup and build process..."
          pip install sphinx sphinx-markdown-builder

          echo "Sphinx source directory will be: ${SPHINX_SOURCE_DIR}"
          echo "Sphinx build directory will be: ${SPHINX_BUILD_DIR}"
          
          SPHINX_MARKDOWN_OUTPUT_DIR="${SPHINX_BUILD_DIR}/markdown"

          echo "Creating Sphinx source directory: ${SPHINX_SOURCE_DIR}"
          mkdir -p "${SPHINX_SOURCE_DIR}"

          echo "Creating Python script (generate_conf.py) to generate conf.py..."
          # The 'cat' command below ends with '> generate_conf.py'.
          # The Python script ('import os' etc.) MUST start on the NEXT line.
          cat << 'END_OF_PYTHON_SCRIPT' > generate_conf.py
          import os
            import datetime

            # This script is run from the repository root.
            # The SPHINX_SOURCE_DIR_ENV environment variable is expected to be set 
            # by the calling shell script (the 'run:' block in the GitHub Action).
            sphinx_conf_dir_path = os.getenv('SPHINX_SOURCE_DIR_ENV') 
            if not sphinx_conf_dir_path:
                print('Error: SPHINX_SOURCE_DIR_ENV environment variable not set for Python script generate_conf.py.')
                exit(1)

            current_year = datetime.date.today().year

            config_content = f"""# Generated conf.py
            import sys
            import os

            sys.path.insert(0, os.path.abspath('../src'))

            project = 'My Project Documentation' # TODO: Customize project name
            copyright = f'{current_year}, Your Name/Org' # TODO: Customize copyright holder

            extensions = [
                'sphinx.ext.autodoc',
                'sphinx.ext.napoleon',
                'sphinx_markdown_builder',
            ]
            napoleon_google_docstring = True
            napoleon_numpy_docstring = False 
            html_theme = 'alabaster'
            exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store'] 
            """

            conf_file_full_path = os.path.join(sphinx_conf_dir_path, 'conf.py')
            try:
                os.makedirs(sphinx_conf_dir_path, exist_ok=True) 
                with open(conf_file_full_path, 'w') as f:
                    f.write(config_content.strip())
                print(f'Successfully generated Sphinx conf.py at {conf_file_full_path}')
            except Exception as e:
                print(f'Error writing conf.py in generate_conf.py: {e}')
                exit(1)

          END_OF_PYTHON_SCRIPT
# ^^^^^^^^^^^^^^^^^^^^ CRITICAL DELIMITER LINE ABOVE ^^^^^^^^^^^^^^^^^^^^
# This `END_OF_PYTHON_SCRIPT` delimiter MUST be on a line by itself,
# starting at COLUMN 1 (no leading spaces/tabs), and with NO trailing spaces/tabs.

          echo "Executing Python script (generate_conf.py) to generate conf.py..."
          SPHINX_SOURCE_DIR_ENV="${SPHINX_SOURCE_DIR}" python generate_conf.py
          
          if [ $? -ne 0 ]; then
            echo "Python script generate_conf.py failed."
            exit 1
          fi
          rm generate_conf.py

          echo "Creating Sphinx index.rst in ${SPHINX_SOURCE_DIR}"
          cat <<EOL > "${SPHINX_SOURCE_DIR}/index.rst"
Welcome to My Project's Documentation!
======================================
This documentation is automatically generated from the Google-style docstrings
in the Python modules found in the \`./src\` directory.

.. toctree::
   :maxdepth: 2
   :caption: API Reference:

   api_modules
EOL

          echo "Creating Sphinx api_modules.rst in ${SPHINX_SOURCE_DIR} to list modules from ./src"
          API_MODULES_FILE="${SPHINX_SOURCE_DIR}/api_modules.rst"
          echo "API Modules" > "${API_MODULES_FILE}"
          echo "===========" >> "${API_MODULES_FILE}"
          echo "" >> "${API_MODULES_FILE}"

          if [ -d "./src" ]; then
            find ./src -name "*.py" -not -name "__init__.py" | sed -e 's|^\./src/||g' -e 's|\.py$||g' -e 's|/|\.|g' | sort | while read module_path; do
              if [ -n "${module_path}" ]; then
                echo "Adding module to api_modules.rst: ${module_path}"
                echo ".. automodule:: ${module_path}" >> "${API_MODULES_FILE}"
                echo "   :members:" >> "${API_MODULES_FILE}"
                echo "   :undoc-members:" >> "${API_MODULES_FILE}"
                echo "   :show-inheritance:" >> "${API_MODULES_FILE}"
                echo "" >> "${API_MODULES_FILE}"
              fi
            done
          else
            echo "Warning: ./src directory not found. No API modules will be documented." >> "${API_MODULES_FILE}"
          fi

          echo "Running Sphinx build (Markdown output)..."
          sphinx-build -M markdown "${SPHINX_SOURCE_DIR}" "${SPHINX_BUILD_DIR}"
          if [ $? -ne 0 ]; then
            echo "Sphinx build command failed."
            exit 1
          fi
          
          echo "Listing generated Markdown files in ${SPHINX_MARKDOWN_OUTPUT_DIR}:"
          ls -R "${SPHINX_MARKDOWN_OUTPUT_DIR}" || echo "Sphinx Markdown output directory not found or empty."

      - name: Checkout Wiki repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: wiki

      - name: Sync Sphinx docs into wiki
        env:
            SPHINX_BUILD_DIR: "_build"
        run: |
          SPHINX_MARKDOWN_SYNC_SOURCE_DIR="${SPHINX_BUILD_DIR}/markdown" 

          echo "Preparing to sync from ${SPHINX_MARKDOWN_SYNC_SOURCE_DIR} to wiki directory."

          if [ -d "${SPHINX_MARKDOWN_SYNC_SOURCE_DIR}" ] && [ -n "$(ls -A ${SPHINX_MARKDOWN_SYNC_SOURCE_DIR})" ]; then
            echo "Syncing Sphinx Markdown output to wiki..."
            rsync -av --delete --exclude='.buildinfo' "${SPHINX_MARKDOWN_SYNC_SOURCE_DIR}/" wiki/
          else
            echo "Warning: Sphinx Markdown output directory is empty or does not exist. Nothing to sync."
          fi
          echo "Listing contents of wiki directory after sync:"
          ls -R wiki || echo "Wiki directory not found."

      - name: Publish to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}