name: Generate & Publish Wiki Docs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Install Pydoc-Markdown via pipx
      - name: Install Pydoc-Markdown
        run: |
          python -m pip install --upgrade pip 
          python -m pip install pipx 
          pipx install pydoc-markdown 

      # 3. Generate Markdown docs
      - name: Generate Markdown via Pydoc-Markdown
        run: |
          rm -rf Documentation && mkdir Documentation
          # Single-file approach:
          pydoc-markdown -I . -p src \
            '{ renderer: { type: markdown, filename: "Documentation/api.md" } }'
          # OR, multiple-file approach:
          # for module in $(find src -name '*.py' -not -name '__init__.py' \
          #                 | sed -e 's|^src/||' -e 's|\.py$||' -e 's|/|.|g'); do
          #   pydoc-markdown -I . -m "$module" '{ renderer: { type: markdown } }' \
          #     > "Documentation/${module}.md"
          # done 

      # 4. Checkout the Wiki repo
      - name: Checkout Wiki repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: wiki                                          

      # 5. Sync docs into wiki (mirror deletes too)
      - name: Sync docs into wiki
        run: |
          rsync -av --delete Documentation/ wiki/ 
          ls -R wiki/

      # 6. Publish to Wiki
      - name: Publish to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "wiki" 
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}