name: Generate & Publish Wiki Docs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Install Pydoc-Markdown via pipx
      - name: Install Pydoc-Markdown
        run: |
          python -m pip install --upgrade pip 
          python -m pip install pipx 
          pipx install pydoc-markdown 

      # 3. Generate Markdown docs
      - name: Generate Markdown via Pydoc-Markdown
        run: |
          rm -rf Documentation && mkdir Documentation

          # Single-file approach [-I == Path to search in, -p == Package to document]:
          # Home.md is the default page of the Github native wiki (so it is overwritten each time)
          pydoc-markdown -I . -p src \
            '{ renderer: { type: markdown, 
                           descriptive_class_title: false,
                           add_module_prefix: false,
                           filename: "Documentation/Home.md" } }'
          
            # OR, multiple-file approach? (Not tested yet):
          # for module in $(find src -name '*.py' -not -name '__init__.py' \
          #                 | sed -e 's|^src/||' -e 's|\.py$||' -e 's|/|.|g'); do
          #   pydoc-markdown -I . -m "$module" '{ renderer: { type: markdown } }' \
          #     > "Documentation/${module}.md"
          # done 

      # 4. Checkout the Wiki repo
      - name: Checkout Wiki repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki                                          

      # 5. Sync docs into wiki 
      - name: Sync docs into wiki
        run: |
          rsync -av Documentation/ wiki/ 
          ls -R wiki/

      # 6. Publish to Wiki
      - name: Publish to Wiki
        run: |
          cd wiki/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto Wiki Generated"
          git push