name: Generate & Publish Wiki Docs

on:
  push:
    branches: [ main ]

permissions:
  contents: write # For checking out code, wiki, and pushing to wiki

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build tools and lazydocs
        run: |
          pip install git+https://github.com/ml-tooling/lazydocs.git@main
          rm -rf Documentation
          lazydocs ./src --output-path=Documentation
          echo "Listing generated documentation files:"
          ls -R Documentation || echo "Documentation directory not found or empty."

      - name: Checkout Wiki repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # PAT with 'repo' scope
          path: wiki

      - name: Sync docs into wiki
        run: |
          if [ -d "Documentation" ] && [ -n "$(ls -A Documentation)" ]; then
            echo "Syncing Documentation/ to wiki/"
            rsync -av --delete Documentation/ wiki/
          else
            echo "Warning: Documentation directory is empty or does not exist. Nothing to sync."
          fi
          echo "Listing contents of wiki directory after sync:"
          ls -R wiki || echo "Wiki directory not found."

      - name: Publish to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}