name: Generate and Update Wiki

on:
  push:
    branches:
      - main # Or your default branch, e.g., master

jobs:
  build_and_update_wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows actions/checkout to push to the wiki of the same repo

    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4
        with:
          path: main_repo # Checkout main repo into 'main_repo' directory

      - name: Checkout Wiki Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki_repo # Checkout wiki into 'wiki_repo' directory
          # Default GITHUB_TOKEN with permissions.contents: write is sufficient here

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify your desired Python version

      - name: Install pydoc-markdown with pipx and Verify
        env:
          # Explicitly set PIPX_HOME for where pipx stores its environments
          PIPX_HOME: ${{ runner.temp }}/.pipx_home_user 
          # Explicitly set PIPX_BIN_DIR to where executables should be linked
          PIPX_BIN_DIR: /home/runner/.local/bin # Matches your Python script's expectation
        run: |
          # Install pipx for the user
          python -m pip install --user pipx
          
          # Add the user's local bin (where pipx itself and its shims will go) to PATH
          # for THIS script block AND for subsequent steps via GITHUB_PATH.
          # GITHUB_PATH prepends, which is what we want.
          echo "${PIPX_BIN_DIR}" >> $GITHUB_PATH
          export PATH="${PIPX_BIN_DIR}:${PATH}"
          
          echo "--- Current PATH: $PATH"
          echo "--- Expected pipx executable location: ${PIPX_BIN_DIR}/pipx"
          echo "--- Location of 'pipx' command being used: $(which pipx || echo 'pipx not found')"
          echo "--- PIPX_HOME is set to: $PIPX_HOME"
          echo "--- PIPX_BIN_DIR is set to: $PIPX_BIN_DIR"

          # Verify pipx installation and ensure it's the user-installed one
          if ! command -v pipx &> /dev/null || ! pipx --version | grep -q '[0-9]'; then
            echo "User-installed pipx command not found or not working. Exiting."
            exit 1
          fi

          echo "Uninstalling any existing pydoc-markdown managed by this pipx (if any)..."
          pipx uninstall pydoc-markdown || echo "pydoc-markdown was not previously installed by this pipx, or uninstall failed."

          echo "Installing pydoc-markdown==4.8.0 with user pipx (verbose)..."
          # The PIPX_HOME and PIPX_BIN_DIR env vars should guide this pipx instance
          pipx install pydoc-markdown==4.8.2 --verbose
          
          echo "--- pydoc-markdown 4.8.0 installation attempt by pipx complete ---"
          
          echo "--- Verifying pipx environment post-install ---"
          pipx list --verbose || echo "pipx list command failed"
          
          echo "--- Checking contents of ${PIPX_BIN_DIR} ---"
          if [ -d "${PIPX_BIN_DIR}" ]; then
            ls -la "${PIPX_BIN_DIR}"
            echo "Attempting to run ${PIPX_BIN_DIR}/pydoc-markdown --version (if it exists):"
            if [ -f "${PIPX_BIN_DIR}/pydoc-markdown" ]; then
              "${PIPX_BIN_DIR}/pydoc-markdown" --version
            else
              echo "${PIPX_BIN_DIR}/pydoc-markdown NOT FOUND. This is the critical issue."
              exit 1 # Fail the step if our target executable isn't there
            fi
          else
            echo "${PIPX_BIN_DIR} directory NOT FOUND."
            exit 1 # Fail if the bin dir itself is missing
          fi
          
          echo "--- Checking which pydoc-markdown is found by bash NOW (should be ours) ---"
          which pydoc-markdown || echo "pydoc-markdown still not found by 'which' (unexpected)"

      - name: Generate Markdown and Prepare Wiki Content
        working-directory: ./main_repo # Run the script from the main repo's context
        run: |
          # The script expects the absolute path to the wiki_repo as an argument
          # GITHUB_WORKSPACE is the root of the checkout space
          python scripts/update_wiki.py "${{ github.workspace }}/wiki_repo"
        env:
          # Any other environment variables your script might need can go here
          # For example, if you made PYDOC_CONFIG_FILE configurable via env var
          PYTHONIOENCODING: "UTF-8" # Good practice for string handling

      - name: Commit and Push to Wiki
        working-directory: ./wiki_repo # Operate within the wiki_repo directory
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com" # Standard GH Actions bot email
          
          # Check if there are changes to commit
          # `git status --porcelain` outputs machine-readable status. If it's empty, no changes.
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Automated wiki generation from main branch [skip ci]"
            echo "Pushing changes to wiki..."
            git push
            echo "Wiki updated and pushed."
          else
            echo "No changes to commit to the wiki."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Explicitly pass, though often available by default